name: Wealthsimple Toolbox Script
description: Run scripts using Wealthsimple's Actions Toolbox (internal only)
author: Wealthsimple
inputs:
  script:
    required: true
    description: The script to run
  sonarqube_host:
    required: false
    description: The SonarQube hostname
  sonarqube_token:
    required: false
    description: The SonarQube token
outputs:
  result:
    description: The return value of the script, stringified with `JSON.stringify`
runs:
  using: 'node12'
  main: 'dist/index.js'
